### ISSUE TITLE
Doesn't work with Synapse 3

### ISSUE THREAD

**Issue by Naxterra** [roxaskeyheart/Chromatics#101]
I am using Chromatics 2.4.7 on my Razer Blackwidow Chroma v2 keyboard with Razer Synapse 3 ver 3.4.415.41818 for Final Fantasy 14.

Problem is even though Chromatics is enabled in Chroma Studio, it is not working. I am only seeing my Chroma effects from Razer Chroma studio. If I close Synapse 3 Chromatics works. I tried shutting down all lights via brightness off in Synapse, tried several default chroma effects but still nothing.

What can I do?

**Comment by logicallysynced** [comment]
That’s an odd issue as Razer Chroma apps should take priority over Synapse profiles. I would look at the Chroma Apps list in Synapse and see if you can turn on and off integrations to see if that affects anything?

If all else fails you can try reinstalling Synapse 3 just in case.

The fact that you say it works when Synapse 3 is closed leads me to believe Chroma Studio is taking priority control of the Razer SDK so the problem is in Synapse somewhere.

I can look at it tomorrow myself but if you’re still stuck there might be someone in the Chromatics Discord who might know a fix?

**Comment by Naxterra** [comment]
Hello

I reinstalled Razer Synapse 3 several times and FF14 once. I also contacted Razer support about this and they told me to delete Synapse and FF14 folders, then reinstall them again which I did.

I disabled Chromatics in Chroma Connect, ran FF14 and nothing changed. It used my Chroma lighting. Then I enabled it again, it is like lightning storm on my keyboard. It looks like both are trying to overwrite others.

**Comment by logicallysynced** [comment]
Reinstalling FFXIV should not have any effect so there should be no need to worry about that.

When uninstalling Synapse you may need to additionally uninstalled Razer SDK from Add/Remove programs. Synapse does install this automatically but doesn’t always remove it.

I’ll see if I can reproduce the issue though tomorrow.

**Comment by Naxterra** [comment]
https://share.icloud.com/photos/0y--w0hiYkveDEShTEP6yN_Og

Here is a video of what happens

**Comment by Naxterra** [comment]
Any updates?
