### ISSUE TITLE
Any ETA on DX 11 Support?

### ISSUE THREAD

**Issue by zarry** [roxaskeyheart/Chromatics#29]
Hello,

This looks really promising thank you for working on it.  I mainly run the game in DX 11 and was wondering if you have an ETA for DX 11 support?.  If you need a tester on DX 11, I can gladly help.

**Comment by logicallysynced** [comment]
So currently Chromatics has all the code implemented to support DX11 already, however we are waiting on an external library which handles all the FFXIV data processing and the developers of said library have been working towards DX11 support for some time now.

It's worth noting that with the release of Stormblood (4.0) approaching rapidly, it is highly likely that DX9 compatibility will break with the new expansion. Therefore our top priority, and the developers of said library will more than likely be focussed on restoring support for 4.0 DX9 before resuming work on DX11.

I apologise for the inconvinience this causes, it's a bit of a complicated process when it comes to reading game data safely unfortunately.

I will post here if I get any updates however.

**Comment by zarry** [comment]
Thank you for the prompt reply.  Absolutely no need to apologize, you are doing great work.  If you need any testing, please let me know.

**Comment by joelwhokillz** [comment]
Unlike the above user, I'm more pesky as a user, and came (and made an account) specifically to complain at you. 

Why are you guys putting all your attention on creating this potentially awesome program and bottlenecking it by focusing on a dying API that isn't even going to be supported by anyone, let alone FF14 in the more than likely NEAR future? 

DX12 is a thing now, it's going to replace DX11 faster than DX11 will then turn around and completely replace DX9, and with Squeenix dropping PS3 completely, it's a literal guarantee that the next step will be dropping DX9 in favour of 11 and 12.

So reiterating my earlier question, why are you guys focusing all your efforts on developing this for DX9 and not DX11? Does anyone even use DX9 in 2017 knowing that it gives extremely inferior graphics and performance? I got super excited when I found this, downloaded it, and then turned it on to realize it's completely useless. 

/rant. 

Thank you for your work though, if you guys actually develop a working product this could be super badass.

**Comment by logicallysynced** [comment]
@joelwhokillz Chromatics 2.0 was built with support for both DX9 and DX11 from the beginning. From our coding perspective, it is ready to go.

The problem is, as mentioned briefly above, we use an [external library/plugin](https://github.com/Icehunter/ffxivapp-memory) to bring in all the FFXIV data and that plugin does not yet support parsing DX11 data from the game. Without that ability our plugin is limited to DX9 support only. As soon as they implement their DX11 code, it will be a very quick process to activate it on Chromatics.

Because my own personal "memory reading" programming skills are quite inadequate at this point in time, implementing our own system is out of the question currently; if a developer who has those skills comes along and offers to help, I would most likely completely build the parsing into Chromatics natively without the need for external libraries.

Sorry for the inconvenience, I too play the game on DX11 most of the time so it is a problem for us too.

**Comment by joelwhokillz** [comment]
Well.... If that's the only reason then ok. I did read that, but I saw you saying that in 4.0 you would be focusing on fixing DX9 and I was like "DX9 doesn't even need to be a thing!!" lol

Well as the OP is over a month old now, do we have any news on when this ELP is going to be implemented? I really wanna use this app because I have these sweet chroma KB/M and after Diablo 3's semi native support of unique lighting I would LOVE to use it in FF14 (Just came back for Stormblood). 

I just don't know if I want it enough to play in DX9 mode lol

**Comment by logicallysynced** [comment]
When Stormblood comes out, it's pretty safe to assume all memory reading apps/plugins will break (ACT, FFXIV-Memory, etc.) due to the significant changes inbound. My assumption is that FFXIV-Memory's (the plugin we use for bringing in FFXIV data) team will focus on restoring functionality for DX9 first and then DX11.

From our perspective, since Chromatics is build DX-independent, our 4.0 update will patch both DX9 and DX11 aspects of Chromatics, so if/when FFXIV-Memory brings out DX11 support, our code will be good to go.

As of this time I have no ETA from Icehunter on DX11 support from FFXIV-Memory however. :(

**Comment by joelwhokillz** [comment]
Well that's unfortunate. I went ahead and switched it over to DX9 mode so I can at least test this app out a lil, but I'll definitely be eager for the full experience so to speak. 

Sorry for the intial rant, I wasn't angry, just miffed cos I got super excited and then smacked into the walls of reality. Lmao!

**Comment by logicallysynced** [comment]
It's all good, unfortunately I haven't been able to work on this as much as I would like due to IRL commitments and being a two-person team, so Chromatics still remains in Beta for the time being. >_<; I appreciate the feedback however, keeps me motivated 👍

**Comment by danielrouleau** [comment]
I agree DX11 support would be great as that is also what I use 99% of the time. I hadn't seen any action on ffxiv-app repos in a while so I guess we will see if he picks it back up after the expansion. I know FFXIVAPP used to support DX11 when I used it before switching to ACT.

**Comment by bsides** [comment]
It appears that they have updated the library, did you notice? I don't know if it's DX11 compatible, just that ACT is working again so I believe it is.

**Comment by zarry** [comment]
@roxaskeyheart Any update on this?  Based on the readme of https://github.com/Icehunter/ffxivapp-memory it looks to support DX 11.  Any luck getting that into chromatics?

**Comment by danielrouleau** [comment]
I'll have a go at pulling in the new ffxivapp-memory module and seeing if I can get it working on DX11
edit: things look promising in Corsair emulator, can't test Logitech b/c FFXIV is overriding the API calls for Chromatics and I don't see a way in-game to disable lighting.

**Comment by zarry** [comment]
@danielrouleau I can test on razer as needed.

**Comment by logicallysynced** [comment]
DX11 and Stormblood support has now been added. Please refer to the release section or update from within Chromatics.

https://github.com/roxaskeyheart/Chromatics/releases

Please note that Chromatics is still in beta and bugs may appear.
