### ISSUE TITLE
Logitech SDK failed to load

### ISSUE THREAD

**Issue by Ixeuticus** [roxaskeyheart/Chromatics#35]
Hi
I have Logitech Gaming Software installed, where can I get the SDK?
Thanks

> Starting Chromatics Version 2.2.1 (Beta)
> Searching for devices.chromatics..
> Attempting to load devices.chromatics..
> devices.chromatics loaded.
> Searching for settings.chromatics..
> Attempting to load settings.chromatics..
> settings.chromatics loaded.
> Searching for mappings.chromatics..
> Attempting to load mappings.chromatics..
> mappings.chromatics loaded.
> Architecture: x64
> The Razer SDK (RzChromaSDK64.dll) Could not be found on this computer. Please install Synapse and restart ACT if you wish to use Chromatics with Razer devices.
> Attempting to load CUE SDK..
> CUE SDK failed to load. EX: Error in the application.
> Attempting to load Logitech SDK..
> Logitech SDK failed to load.
> Attempting to load LIFX SDK..
> LIFX SDK Loaded
> DX11 Initiated
> Attached to FFXIV

**Comment by danielrouleau** [comment]
Ah, we will need to move the 64-bit Logitech LED SDK dll in the installer, thanks for catching this. I will note, however, that Logitech isn't currently supported (as of 4.0) because of limitations with FFXIV and Chromatics both attempting to send colors to the Logitech devices at the same time, and there is not currently a way in-game to disable the default colors coming from FFXIV.

**Comment by Bronsens** [comment]
There is a way of disabling LED Backlighting in LGS.
Under Applets there should now be a ffxiv_dx11 Applet just untick the LED Backlighting.

I'm wondering if this will also resolve the conflict.

**Comment by logicallysynced** [comment]
We fixed Logitech support in 2.2.4 and are currently ironing out some bugs. It should work however.
