### ISSUE TITLE
Logitech Device not Detected

### ISSUE THREAD

**Issue by strevorrow** [roxaskeyheart/Chromatics#39]
I have a Logitech G910 Keyboard and a Logitech G502 Mouse, I have the "LED Backlighting" checkbox unchecked in LGS but Chromatics will not detect either device.

Debug Console Output below

Starting Chromatics Version 2.2.4 (Beta)
Searching for devices.chromatics..
Attempting to load devices.chromatics..
devices.chromatics loaded.
Searching for settings.chromatics..
Attempting to load settings.chromatics..
settings.chromatics loaded.
Searching for mappings.chromatics..
Attempting to load mappings.chromatics..
mappings.chromatics loaded.
Attempting to load Razer SDK..
Architecture: x64
The Razer SDK (RzChromaSDK64.dll) Could not be found on this computer. Please install Synapse and restart ACT if you wish to use Chromatics with Razer devices.
Razer SDK failed to load.
Attempting to load Logitech SDK..
Logitech SDK Loaded
Attempting to load CUE SDK..
CUE SDK failed to load. EX: Error in the application.
CUE SDK failed to load.
Attempting to load LIFX SDK..
LIFX SDK Loaded
Attempting Attach..
DX11 Initiated
Attached to FFXIV
Game Running ([Char name redacted])
Watchdog Started

**Comment by logicallysynced** [comment]
Just to confirm, have you enabled the "Allow games to control illumination" setting within LGS?

**Comment by strevorrow** [comment]
I do have that option enabled. I'll add some screenshots of my configurations.

**Comment by strevorrow** [comment]
![image](https://user-images.githubusercontent.com/6816605/27989526-759f16ac-6408-11e7-8ca7-24b1639c0174.png)
![image](https://user-images.githubusercontent.com/6816605/27989532-a860a3f8-6408-11e7-8b66-c3c2d64208a6.png)
![image](https://user-images.githubusercontent.com/6816605/27989535-b231565c-6408-11e7-9ba6-74c3657388e6.png)
![image](https://user-images.githubusercontent.com/6816605/27989556-f18f07e0-6408-11e7-803e-99f07fb0558c.png)

**Comment by logicallysynced** [comment]
Will investigate. Thanks for the details!

**Comment by mnemyx** [comment]
I wanted to chime in since I also have a G910/G502 and am experiencing the same thing.

It did change my keyboard+mouse lighting scheme but no actual lighting feedback.

![chromatics_2017-07-08_20-33-50](https://user-images.githubusercontent.com/770706/27990980-2ee9c0f8-641d-11e7-9876-dcce73a1ccac.png)
![chromatics_2017-07-08_20-34-15](https://user-images.githubusercontent.com/770706/27990983-2ef613c6-641d-11e7-9c6c-704d126a188a.png)
![chromatics_2017-07-08_20-34-36](https://user-images.githubusercontent.com/770706/27990982-2ef5711e-641d-11e7-945f-dbd77706ae14.png)
![lcore_2017-07-08_20-34-57](https://user-images.githubusercontent.com/770706/27990981-2ef5542c-641d-11e7-88fc-e53dca674017.png)
![lcore_2017-07-08_20-35-06](https://user-images.githubusercontent.com/770706/27990984-2ef75394-641d-11e7-8e31-b471d7a17f32.png)
![lcore_2017-07-08_20-35-12](https://user-images.githubusercontent.com/770706/27990985-2f09d686-641d-11e7-9eda-1bc05dcff634.png)

On the plus side, the ARX plugin on my phone seems to be doing okay, albeit some lag.

**Comment by logicallysynced** [comment]
Can you send me a screenshot of the Chromatics directory please?

Additionally did you use the Installer or Portable version?

**Comment by strevorrow** [comment]
I used the installer. Screenshots below!
![image](https://user-images.githubusercontent.com/6816605/27995536-05b5b472-649e-11e7-9446-6e37ee9f1e54.png)
![image](https://user-images.githubusercontent.com/6816605/27995539-105602ec-649e-11e7-9846-e4a10c08b0d3.png)

**Comment by logicallysynced** [comment]
We have found a bug in the Logitech implementation of Chromatics. We're working on a hotfix right now.

**Comment by logicallysynced** [comment]
Please try Version 2.2.5 and see if this resolves your problem. Check out the new Logitech Conflict Control feature in particular.

https://github.com/roxaskeyheart/Chromatics/releases

**Comment by strevorrow** [comment]
It looks to be working with the latest version, thanks!

**Comment by mnemyx** [comment]
This seems to be working on my end as well. Thank you!

**Comment by logicallysynced** [comment]
Most excellent! 👍
