### ISSUE TITLE
Some features don't seem to work

### ISSUE THREAD

**Issue by LeonBlade** [roxaskeyheart/Chromatics#47]
Hello, love the software and looking forward to creating my own plugins.

However, I noticed that some of the ARX templates don't seem to work.  Is this intentional?  From what I saw in the developers section, you seem to have some support for these features, but perhaps not?

**Comment by logicallysynced** [comment]
ARX plugins are still very much in an alpha stage at the moment. I have been meaning to remove non-functioning plugins from the list.

I've been looking for a volunteer developer to get onto the team to help me with all the ARX stuff since I've been focused quite a bit on the core functionality and bug fixes as of late. I'm hoping to work on ARX stuff soon though.

**Comment by LeonBlade** [comment]
I'd love to help out with the project any way I can.  I'll look into the ARX stuff and see if it's something I'm capable of handling.
