### ISSUE TITLE
Re-opening old issue (Razer Naga)

### ISSUE THREAD

**Issue by tidyu** [roxaskeyheart/Chromatics#6]
Original: https://github.com/roxaskeyheart/Chromatics/issues/4

Hey,

I meant to add to the last but had a busy few days.

I've tried installing the Dev kit but it keeps saying:

Error opening file for writing:
.......\RzAPIChromaSDK.dll

I have the latest Synapse installed already, and I've seen the dll in the location you linked in the last post.

Any ideas what could be causing this?

Regards,
Tidyu

**Comment by logicallysynced** [comment]
This error occurs when Synapse is running when you try and install the SDK. If you open Task manager and kill the RzSynapse.exe process tree before running the installer, it should install without errors. You will need to restart your computer (or Synapse) after the installation is complete though.

**Comment by tidyu** [comment]
I've done that, and restarted. Chromatics is enabled for my Logitech keyboard, but I get the old RzChromaSDK64.dll not found error.

The thing is though, the DLL is actually there.

**Comment by logicallysynced** [comment]
The DLL missing error is caused by one of two things. The first is when the actual .dll file is missing from your Program Files folder and the second is when the SDK hasn't been registered in the computer's registry.

Normally both of these things occur when installing Razer Synapse so I'm unsure as to why you're having issues. I'm guessing it could be anything from a permissions issue to an anti-virus blocking part of the installation.

Try and download the [Developer Package](http://developer.razerzone.com/chroma/download/) from Razer's developer portal and inside you will find two .reg files. Open the one that says **Enable SDK support (x64).reg** as an administrator to force the SDK to register in the system registry.

Also make sure you're running ACT as an administrator as to prevent any unintentional permission issues.

**Comment by tidyu** [comment]
Perfeect! That fixed it :).

Thank you very much for your help!

**Comment by leonardoInf** [comment]
If you are using Synapse 3 consider downloading the SDK seperately : https://assets.razerzone.com/dev_portal/downloads/Razer_Chroma_SDK_Core_v1.10.6.exe (also available from the link @roxaskeyheart has posted)
