### ISSUE TITLE
Turn on lights even if game is not running

### ISSUE THREAD

**Issue by RustyPedrosa** [roxaskeyheart/Chromatics#64]
Any time the game is not running and Chromatics says "Waiting for Game Launch," could the keyboard backlights be turned on?

Right now, at least after closing the game, my keyboard stays "stuck" with whatever keys were lit when the game closed.  But it would be especially nice to have lights before the game is started, instead of having the entire keyboard be dark.  

Doesn't matter to me how it's done - make the whole keyboard one color, or pretend game is running + all gauges are full, etc, 

I just don't like completely dark keys.  So, for example, I set all the empty bars/blank keys to dark gray.

This is a really cool program, and I wouldn't mind leaving it running all the time on my gaming machine instead of CUE, if this can be done.

**Comment by RustyPedrosa** [comment]
Looked through code and saw all the disabled API calls and stuff for corsair devices, so I assume this is already known / being worked on.  If I can help with any testing (sounds like you don't have a Corsair device?), let me know.

**Comment by logicallysynced** [comment]
This is a little bit more complicated to do then it sounds but it’s not impossible. Of course setting the colour while idle would be pretty easy but getting it to restore CUE lighting would be more ideal..

As a temporary solution you can use the “Enable SDK” checkbox (might be called something similar) in CUE2 software to toggle control between Chromatics and CUE2?

I’ll look into a feasible solution though, but I’m taking a bit of a hiatus from coding due to IRL happenings at the moment.. the only update I might push out in the near future is for 4.2 compatibility.

**Comment by RustyPedrosa** [comment]
I'll play with it once I get another keyboard in.  My K95 RGB Platinum had the sticking/grinding volume wheel issue and I wasn't happy with the brown switches anyway, so I returned it.  Got the Razer Blackwidow Chroma V2 and absolutely loved the green switches, but it had a defective cable.  Maybe I need to get away from gaming keyboards, lol.. but I really love the Corsair non-standard layout/keysizes (bottom row and especially the top row where F1 is shifted left, closer to the Esc key and slightly above the 1 key).

Anyway, IRL sucks, but hang in there.  Friends/family/etc come first.  Especially above keyboard rgb lighting, lol.

**Comment by logicallysynced** [comment]
The latest version now uses the Base Colour as a palette for when FFXIV is not running or Chromatics is booting.
