### ISSUE TITLE
Higher refreshrate for enemy data in ARX controll / issue with razer keyboard lighting effects

### ISSUE THREAD

**Issue by ghost** [roxaskeyheart/Chromatics#89]
Hey,

as the title says, is it possible to create a higher refreshrate for enemy data in the player HUD template in logitech ARX app? Just as an example: i was fighting against gaius. he has shown up as a marked enemy at 125k life (around 80%). after we killed him (synced mode) the app still has shown the amount of 125k life left. 

Now my razer issue:
since today (20th of september 2018) my razer blackwidow chroma v2 isn't showing anymore lighting effects. tryed using an older version of chromatics but it didn´t work aswell. Maybe you could help me to fix this.

**Comment by logicallysynced** [comment]
ARX is unfortunately like that and there will be some latency between the game and the smartphone.

The reason Chromatics isn’t working right now is that it hasn’t been updated for patch 4.4 yet. I’m currently working on an update for it but it might be a couple of days still.

**Comment by hugarburdur** [comment]
I experience the same issue with the current stable branch. All the info are refreshed smoothly in ARX, accept for the target data. In many cases, the target info (name, lvl, etc.) aren't showed at all. And when they are, they are not refreshed (ie. the HP don't decrease when ennemy is attacked).
I doubt it's due to ARX latency because all the other info (ie. player's data like HP, MP...) are refreshed smoothly.

**Comment by logicallysynced** [comment]
Closing due to the impending release of Chromatics 3.x.

Chromatics 3 is a complete rebuild of Chromatics from the ground up, and as such most previous issues are likely now invalidated. Please try the new version when released and then report any new issues as they occur.
